version: '3.8'

services:
  # 1. El contenedor de la Base de Datos
  db:
    image: postgres:15-alpine
    container_name: ticketapi-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # NUEVO: Comprueba si PostgreSQL ya está listo para recibir conexiones
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ticketdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. El contenedor de tu API en Spring Boot
  api:
    build: .
    container_name: ticketapi-app
    ports:
      - "8081:8081"
    # NUEVO: Espera explícitamente a que el chequeo de salud de arriba diga "healthy"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ticketdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456

volumes:
  postgres_data: